server:
  port: 9527
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 1KB
  tomcat:
    mbeanregistry:
      enabled: true
    accept-count: 100 # queue capacity
    max-connections: 8192 # tcp connection pool size
    keep-alive-timeout: 60s # keep alive
    connection-timeout: 60s # accept time out
    threads:
      min-spare: 10 # core size
      max: 200 # max size
#  error:
#    whitelabel:
#      enabled: false

spring:
  profiles:
    active: dev
    include:
      - config
  application:
    name: LiteNote
  datasource: # https://jdbc.postgresql.org/documentation
    name: lite_note
    url: jdbc:postgresql://localhost:5432/${spring.datasource.name}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  threads:
    virtual:
      enabled: true
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  messages:
    basename: file:${user.dir}/i18n/messages,classpath:i18n/messages
    cache-duration: 1h
    fallback-to-system-locale: true
  web:
    locale: en
    locale-resolver: accept_header
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
        - file:${preferences.admin.assets-path}
  task:
    execution:
      thread-name-prefix: exec-
      pool:
        core-size: 8
        max-size: 16
        keep-alive: 60s
        queue-capacity: 100
    scheduling:
      thread-name-prefix: cron-
      pool:
        size: 8
  lifecycle:
    timeout-per-shutdown-phase: 1m

logging:
  #  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    name: ${spring.application.name}.log
    path: ${user.dir}
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB

management:
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
      probes: # Kubernetes probes
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: z.note.lite.config.mybatis
