spring:
  profiles:
    active: dev,h2
    include:
      - preferences
      - web
      - server
      - i18n
      - sql
      - actuator
      - logging
      - shutdown
      - task
      - infra
  application:
    name: LiteNote
  datasource:
    name: lite_note
  mvc:
    servlet:
      load-on-startup: 1
    problemdetails:
      enabled: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
