spring:
  web:
    locale: zh
    locale-resolver: accept_header
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/

server:
  compression:
    enabled: true
    min-response-size: 2KB