preferences:
  api:
    login: session
    captcha: graphic
  admin:
    supervisor: admin
    assets-path: ${user.dir}/assets
    uploads-path: /uploads/img/
  portal:
    name: LiteNote
    author: fendoudebb
    keywords: >-
      Java,
      Spring Native,
      Spring Boot,
      Spring Data JPA,
      Spring Security,
      Spring Actuator,
      PostgreSQL,
      Thymeleaf
    description: This is description
    github: https://github.com/fendoudebb/LiteNote
    search:
      tsconfig: jiebacfg
      size: 15
      maxlength: 50
    promotion:
      enabled: true
      text: 扫描下方二维码关注公众号和小程序↓↓↓
      image: /qrcode.png
    comment:
      enabled: false
      type: giscus
      script: |+
        <script src="https://giscus.app/client.js"
                data-repo="fendoudebb/z-blog"
                data-repo-id="R_kgDOJfvN0Q"
                data-category="Announcements"
                data-category-id="DIC_kwDOJfvN0c4CWVNG"
                data-mapping="pathname"
                data-strict="0"
                data-reactions-enabled="1"
                data-emit-metadata="0"
                data-input-position="bottom"
                data-theme="light"
                data-lang="zh-CN"
                crossorigin="anonymous"
                async>
        </script>
    meta:
      - name: a
        content: b
    css:
      - name: highlight
        link: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.3/styles/atom-one-dark.min.css
    js:
      highlight:
        - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.3/highlight.min.js
        - https://cdn.bootcdn.net/ajax/libs/highlight.js/10.7.3/highlight.min.js
      clipboard:
        - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.11/clipboard.min.js
        - https://cdn.bootcdn.net/ajax/libs/clipboard.js/2.0.11/clipboard.min.js
    icp:
      id: 123456
      link: https://beian.miit.gov.cn
    analysis:
      - name: baidu
        value: 123456
        enabled: false
      - name: google
        value: 123456
        enabled: false
infra:
  cache:
    type: jdk
  lock:
    type: jdk
  queue:
    type: jdk
  rate-limiter:
    type: jdk
    duration: 1m
    count: 100
