spring:
  profiles:
    active: dev,h2
    include:
      - server
      - blog
      - jpa
      - actuator
      - logging
      - shutdown
      - concurrency
      - infra
  application:
    name: lite-note
  datasource:
    name: lite-note
  mvc:
    servlet:
      load-on-startup: 1
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
