spring:
  datasource: # https://www.h2database.com/html/features.html
    url: jdbc:h2:mem:${spring.datasource.name};MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;IGNORECASE=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DEFAULT_NULL_ORDERING=HIGH;NON_KEYWORDS=USER;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2
      schema-locations: optional:classpath:sql/schema-h2.sql
      data-locations: optional:classpath:sql/data-h2.sql

