management:
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
      probes: # Kubernetes probes
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
