spring:
  profiles:
    active: dev,h2
    include:
      - config
      - server
  application:
    name: LiteNote
  datasource:
    name: lite_note
  mvc:
    servlet:
      load-on-startup: 1
    problemdetails:
      enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
