spring:
  profiles:
    active: dev,h2
    include:
      - server
      - blog
      - jpa
      - actuator
      - logging
  application:
    name: blog
  datasource:
    name: blog
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
