spring:
  datasource: # https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
    url: jdbc:mysql://localhost:3306/${spring.datasource.name}?createDatabaseIfNotExist=true&logger=com.mysql.cj.log.Slf4JLogger&logSlowQueries=true&slowQueryThresholdMillis=1000&explainSlowQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  sql:
    init:
      platform: mysql
      schema-locations: optional:classpath:sql/schema-mysql.sql
      data-locations: optional:classpath:sql/data-mysql.sql
